### ISSUE TITLE
Keep track of the stopwatch, even if I close the tab.

### ISSUE THREAD

**Issue by ShetlandJ** [ryansonofwilliam/RyzoTestPage#2]
It would be cool if a user could start the time. Close the tab/page/window etc, reopen and the timer would have continued to tick up in their absence.

Steps to achieve, hidden behind "spoiler" tags in case do wants to try to figure it out on dy own:

<details>
  <summary>How to achieve</summary>
   
Look into `localStorage`. LS is used to save things to your browser. For example, if doos ever visited a website that has some pre-filled data in there, that's almost entirely coming from local storage. 

When the user exits the page (look up window.unload), you should save the `Date.now()` and save the status of the stopwatch e.g. `status: 'running'`. Then, when you hit the page again, get the info out of localStorage and check if the stopwatch was running. If it was, work out the difference in time between now and saved exit time, and update the stopwatch accordingly and set it running
</details>

**Comment by ryansonofwilliam** [comment]
Complete at last! Still not sure how to handle tab changing as that seems to pause the timer...
