### ISSUE TITLE
Disable the stop/clear buttons in certain scenarios

### ISSUE THREAD

**Issue by ShetlandJ** [ryansonofwilliam/RyzoTestPage#5]
If the stopwatch isn't in motion, disable the stop button.
If the stopwatch is cleared, disable the stop button and clear button.

![image](https://user-images.githubusercontent.com/29278616/169269380-f5a74b9d-0c88-4334-bc7a-fecbbb680140.png)

**Comment by ryansonofwilliam** [comment]
Sorted.
