### ISSUE TITLE
Properly disable the buttons bouy

### ISSUE THREAD

**Issue by ShetlandJ** [ryansonofwilliam/RyzoTestPage#6]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#:~:text=This%20Boolean%20attribute%20prevents%20the%20user%20from%20interacting%20with%20the%20button%3A%20it%20cannot%20be%20pressed%20or%20focused.

**Comment by ryansonofwilliam** [comment]
Dunzo
